// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wass.Back.Empresa.Rabbit.Context;

namespace Wass.Back.Empresa.Migrations
{
    [DbContext(typeof(EmpresaContext))]
    [Migration("20210609175813_empresasMigration")]
    partial class empresasMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wass.Back.Empresa.Models.Entity.Empresas", b =>
                {
                    b.Property<long>("idEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("aprobador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("digVerficacion")
                        .HasColumnType("int");

                    b.Property<string>("editor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("eliminado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaEdicion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idEstado")
                        .HasColumnType("int");

                    b.Property<string>("mensaje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("razonSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipoAfiliacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("urlLogoEmpresa")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idEmpresa");

                    b.ToTable("Empresas");
                });
#pragma warning restore 612, 618
        }
    }
}
